### PR TITLE
feat(embed): add embed directive

### PR DESCRIPTION
**Pull request by mxth**
Continuing work of #18: update for SU 2.0, add support for any embed content and fix some issues from the last PR.

### CODE REVIEW

**Comment by mxth** [comment]
@caitp @m0t0r please have a look at it

**Comment by caitp** [comment]
the code itself looks okay, just need to try it out

**Comment by caitp** [comment]
I'm not able to check out the patch :( git complains it was split wrong

**Comment by caitp** [comment]
ok, so the pr itself doesn't look totally done yet --- 
screen shot 2015-07-29 at 8 55 20 am --- the demo doesn't work very well. Can we clean this up before merging it in?

**Comment by mxth** [comment]
@caitp It looks fine on my machine (win 8.1 with IE 11, Chrome 44, FF 39). Can I have some debug info?

**Comment by caitp** [comment]
ok, how exactly are you running the demos? is there a grunt task added?

**Comment by mxth** [comment]
I use `http-server` to serve the files. In base dir, type `http-server` then navigate to `http://localhost:8081/src/elements/embed/demo/`

**Comment by mxth** [comment]
@caitp have you got it running yet?

**Comment by caitp** [comment]
I ran it through http-server but couldn't make it work sorry

**Pull request closed without merging**
