### PR TITLE
Changed jshint to eslint

### PR DESCRIPTION
**Pull request by matheuspoleza**
We want to change to es6 with angular 1.4, so to do that its better to use eslint. It include es6 features and its a better lint solution.

Notes:
 - PR has some files changes because I made some chages in indent and max-len. 
- Eslint not have all the features jshint, so some things were taken and subsequently be reviewed, but not something that would prevent the change.

@caitp @m0t0r

### CODE REVIEW

**Comment by caitp** [comment]
Nah, -1 from me on this one

**Comment by matheuspoleza** [comment]
@caitp why?

**Comment by caitp** [comment]
jshint supports es6 just fine, and most of the code changes here look totally bogus. Deleting comments and shit like that, not a good scene

**Comment by matheuspoleza** [comment]
@caitp about the comments i returned that, its not necessary. But other changes was about uggly indent and max-len. And about es6, doesnt support yet, where I know. 

I made this change because I talked to @m0t0r about this. And he talked to do this change

**Comment by caitp** [comment]
Jshint absolutely does support es6 features, where are you getting that it doesn't?

**Comment by matheuspoleza** [comment]
my mistake about "doesn't support", but reading the docs I didn't see anything like this in jshint:
selection_214

Eslint has specific features to es6

**Comment by caitp** [comment]
You can't enable specific es6 features, you get them all as a package. This is fine, and really doesn't  matter. Just set "esversion" to 6

**Pull request closed without merging**
