### PR TITLE
Refactor divider component

### PR DESCRIPTION
**Pull request by frankadrian**
This is the first time im working with TS. Please point out things I can improve. I mainly copied from the button element. Implements #43

### CODE REVIEW

**Comment by m0t0r** [comment]
@frankadrian thanks for your PR, though we are still preparing environment for community contributions. Please remove `demo` folder and `.js` files from your PR and squash your commits into one.

**Comment by frankadrian** [comment]
@m0t0r, sure done.

**Comment by m0t0r** [comment]
@frankadrian LGTM, just one thing. Please change commit message to follow conventional-changelog

```js
refactor(elements): Refactor sm-divider component to TS
```
would work

**Comment by m0t0r** [comment]
@frankadrian there is a conflict with last merge to master, could you please resolve it and I will merge your PR.

**Comment by frankadrian** [comment]
@m0t0r sure, base is up to date.

**Pull request merged**
